# ejbca-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ejbca
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ejbca
  template:
    metadata:
      labels:
        app: ejbca
    spec:
      containers:
        - name: ejbca
          image: keyfactor/ejbca-ce
          ports:
            #- containerPort: 8080
            - containerPort: 8443
          env:
            - name: MYSQL_SERVER
              value: mysql
            - name: MYSQL_USER
              value: root
            - name: MYSQL_PASSWORD
              value: password
---
apiVersion: v1
kind: Service
metadata:
  name: ejbca
spec:
  selector:
    app: ejbca
  ports:
    #    - protocol: TCP
    #      port: 80
    #      targetPort: 8080
    - protocol: TCP
      port: 8443
      targetPort: 8443