apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
data:
  nginx.conf: |
    events {
      worker_connections 1024;
    }
    http {
      include /etc/nginx/mime.types;
      default_type application/octet-stream;
    
      server {
        listen 80;
        server_name ejbca-nuno.myftp.biz;

        location / {
            return 301 https://$host$request_uri;
        }
      }
    
      server {
        listen 80;
        server_name wiki-nuno.myftp.biz;

        location / {
            return 301 https://$host$request_uri;
        }
      }
    
      server {
        listen 80;
        server_name plik-nuno.myftp.biz;

        location / {
            return 301 https://$host$request_uri;
        }
      }
      
      server {
        listen 80;
        server_name onetimesecret-nuno.myftp.biz;

        location / {
            return 301 https://$host$request_uri;
        }
      }

      server {
        listen 443 ssl;
        server_name ejbca-nuno.myftp.biz;
    
        ssl_certificate /etc/nginx/certs/fullchain.pem;
        ssl_certificate_key /etc/nginx/certs/privkey.pem;

        location / {
          proxy_pass http://ejbca.default.svc.cluster.local:8080;
          proxy_set_header Host $host;
          proxy_set_header X-Real-IP $remote_addr;
          proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
          proxy_set_header X-Forwarded-Proto $scheme;
        }
      }

      server {
        listen 443 ssl;
        server_name wiki-nuno.myftp.biz;
    
        ssl_certificate /etc/nginx/certs/fullchain.pem;
        ssl_certificate_key /etc/nginx/certs/privkey.pem;

        location / {
          proxy_pass http://wikijs.default.svc.cluster.local:3000;
          proxy_set_header Host $host;
          proxy_set_header X-Real-IP $remote_addr;
          proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
          proxy_set_header X-Forwarded-Proto $scheme;
        }
      }

      server {
        listen 443 ssl;
        server_name plik-nuno.myftp.biz;
    
        ssl_certificate /etc/nginx/certs/fullchain.pem;
        ssl_certificate_key /etc/nginx/certs/privkey.pem;
    
    
        location / {
          proxy_pass http://plik.default.svc.cluster.local:8080;
          proxy_set_header Host $host;
          proxy_set_header X-Real-IP $remote_addr;
          proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
          proxy_set_header X-Forwarded-Proto $scheme;
        }
      }

      server {
        listen 443 ssl;
        server_name onetimesecret-nuno.myftp.biz;
    
        ssl_certificate /etc/nginx/certs/fullchain.pem;
        ssl_certificate_key /etc/nginx/certs/privkey.pem;

        location / {
          proxy_pass http://onetimesecret.default.svc.cluster.local:7143;
          proxy_set_header Host $host;
          proxy_set_header X-Real-IP $remote_addr;
          proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
          proxy_set_header X-Forwarded-Proto $scheme;
        }
      }
    }

---
apiVersion: v1
kind: Service
metadata:
  name: nginx-proxy
spec:
  type: LoadBalancer
  #externalIPs:
  #  - 3.216.77.168
  #loadBalancerIP: 3.216.77.168
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30144
      protocol: TCP
      name: http
    - port: 443
      targetPort: 443
      nodePort: 30145
      protocol: TCP
      name: https
  selector:
    app: nginx-proxy
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-proxy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-proxy
  template:
    metadata:
      labels:
        app: nginx-proxy
    spec:
      containers:
        - name: nginx
          image: nginx:latest
          ports:
            - containerPort: 80
            - containerPort: 443
          volumeMounts:
            - name: nginx-config-volume
              mountPath: /etc/nginx/nginx.conf
              subPath: nginx.conf
            - name: nginx-certs
              mountPath: /etc/nginx/certs
      volumes:
        - name: nginx-config-volume
          configMap:
            name: nginx-config
        - name: nginx-certs
          secret:
            secretName: nuno.myftp.biz