# wiki-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: wikijs
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wikijs
  template:
    metadata:
      labels:
        app: wikijs
    spec:
      containers:
        - name: wikijs
          image: ghcr.io/requarks/wiki:2
          ports:
            - containerPort: 3000
      env:
        - name: DB_TYPE
          value: "postgres"
        - name: DB_HOST
          value: "postgres"
        - name: DB_PORT
          value: "5432"
        - name: DB_USER
          value: "wikijs"
        - name: DB_PASS
          value: "passw0rd"  # Match this with the PostgreSQL password
        - name: DB_NAME
          value: "wikijs"
---
#apiVersion: v1
#kind: Service
#metadata:
#  name: wikijs
#spec:
#  ports:
#    - port: 3000
#  selector:
#    app: wikijs
