#!/bin/bash

source public-ip-addresses

echo "Create a deployment for nginx"
kubectl apply -f ./Deployments/nginx-deployment.yaml

sleep 2
kubectl get pods -l app=nginx-proxy

echo "Retrieve the external IP address of nginx service"
EXTERNAL_IP=${PUBLIC_ADDRESS[worker-0]}
echo "${EXTERNAL_IP}"

# Assuming you already set the loadBalancerIP in nginx.yaml, no need for further kubectl commands

echo "Make an HTTP request using the external IP address"
curl -I http://"${EXTERNAL_IP}"
