# wiki-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: wikijs
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wikijs
  template:
    metadata:
      labels:
        app: wikijs
    spec:
      containers:
        - name: wikijs
          image: ghcr.io/requarks/wiki:2
          ports:
            - containerPort: 3000
          env:
            - name: MYSQL_SERVER
              value: mysql
            - name: MYSQL_USER
              value: wikijs
            - name: MYSQL_PASS
              value: wikijsrocks
            - name: MYSQL_NAME
              value: wiki
            - name: MYSQL_PORT
              value: "3306"
---
apiVersion: v1
kind: Service
metadata:
  name: wikijs
spec:
  ports:
    - port: 3000
  selector:
    app: wikijs
