# wiki-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: wikijs
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wikijs
  template:
    metadata:
      labels:
        app: wikijs
    spec:
      containers:
        - name: wikijs
          image: ghcr.io/requarks/wiki:2
          ports:
            - containerPort: 3000
          env:
            - name: DATABASE_TYPE
              value: mysql
            - name: DB_HOST
              value: mysql-host
            - name: DB_PORT
              value: "3306"
            - name: DB_USER
              value: wikijs-user
            - name: DB_PASS
              value: your-password
            - name: DB_NAME
              value: wikijs-db