# onetimesecret-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: onetimesecret
spec:
  replicas: 1
  selector:
    matchLabels:
      app: onetimesecret
  template:
    metadata:
      labels:
        app: onetimesecret
    spec:
      containers:
        - name: onetimesecret
          image: dismantl/onetimesecret
          ports:
            - containerPort: 7143
